### PR TITLE
Check license information for relative URLs

### PR DESCRIPTION
**Pull request by dwalluck**

### CODE REVIEW

**Comment by dwalluck** [comment]
I am not sure it's ready yet.

First, I wanted to report the file with a missing mapping. I think this is a regression.

Second, it is trying to handle this case (from the OSGi Core spec): "link - (optional) Provide a URL to a page that defines or explains the license. **If this link is absent, the name field is used for this purpose**. **The URL is relative to the root of the bundle. That is, it is possible to refer to a file inside the bundle**."

**Comment by dwalluck** [comment]
Hopefully, we can get rid of warnings about mapping we can't do anything about. For example, is there even a point to reporting missing mappings for `(name, URL)` pairs such as `(null, LICENSE.txt)` or `(LICENSE.txt, null)` where `LICENSE.txt` doesn't exist? At least though, we can make sure that the file does not exist, and report _that_ as a warning instead.

**Comment by vibe13** [comment]
Hi @dwalluck check this jar out for OSGI compliance and "Name" referencing to a class file inside the jar: https://maven.repository.redhat.com/ga/org/bouncycastle/bcprov-jdk18on/1.78.1.redhat-00002/bcprov-jdk18on-1.78.1.redhat-00002.jar, does that help?

And +1 for getting rid of warnings which we can do nothing about.

**Comment by dwalluck** [comment]
In the spec, I think by "name" they don't mean the Name header, but the "name" part of the Bundle-License. That text is poorly written.

In this JAR, we have Bundle-License: http://www.bouncycastle.org/licence.html which is an absolute URL. I think that it's referring to a case Bundle-License: LICENSE.txt or in the POM license.name = LICENSE.txt.

**Comment by dwalluck** [comment]
@vibe13 I think it's ready for review. It reduces the amount of reported missing mappings, but adds reporting missing license files.

**Review by vibe13 — APPROVED** [review]

**Pull request merged**
