### PR TITLE
[NCL-6202]: Fix reading of GA information in BF PncUtils, refactor Pn…

### PR DESCRIPTION
**Pull request by jbartece**
…cUtils a bit

### CODE REVIEW

**Comment by jbartece** [comment]
@janinko @dwalluck I just realied, that I forgot to cover the case when a build is not Maven. I'm not sure, how should we construct the NVR in that case and even if it makes sense...

**Comment by janinko** [comment]
In DelAn we don't need NVR from PNC build

**Comment by dwalluck** [comment]
@jbartece I think NPM can be made into an NVR easily enough. What other cases do we have to cover?

**Comment by jbartece** [comment]
@dwalluck For now we support only NPM and Maven/Gradle. Scala (SBT) is in research and will be coming in Q1 probably.

**Comment by dwalluck** [comment]
@jbartece The tests are currently failing. I assume that there's nothing to review until the test pass. Or are you still working on this?

I assume that each build system has a unique identifier. Whereas Maven has `<groupId>:<artifactId>:<version>`, NPM has `<name>-<version>` as it would appear in ` package.json`, so we may make use of this unique identifier.

**Comment by jbartece** [comment]
Yes, I'll update it. I switched to other tasks, but I'll get back to this one.

**Comment by michalovjan** [comment]
Dropping after #631 was merged

**Pull request closed without merging**
