### PR TITLE
Explicitly add updated hadoop-hdfs-client to avoid pulling in older v…

### PR DESCRIPTION
**Pull request by rnc**
…ersion of okhttp3

### CODE REVIEW

**Comment by rnc** [comment]
@dwalluck

**Comment by dwalluck** [comment]
@rnc What about replacing this with #778?

**Comment by rnc** [comment]
> @rnc What about replacing this with #778?

I'd be fine with either - both solve the problem of bringing in an older version okhttp3.

**Comment by dwalluck** [comment]
> I'd be fine with either - both solve the problem of bringing in an older version okhttp3.

I'd rather remove an unused dependency rather than try to upgrade it, especially because it's transitive.

The unit tests pass, so I assume there's no issue with removing it. But, unfortunately, the full ITs are not running from PRs or working in general.

**Pull request closed without merging**
