### PR TITLE
Add test for matching license text

### PR DESCRIPTION
**Pull request by dwalluck**

### CODE REVIEW

**Comment by dwalluck** [comment]
@vibe13 So far, I am not able to reproduce the behavior in my test.

**Comment by vibe13** [comment]
hi @dwalluck I think I found the underlying issue. 
The license that could not be detected had also some differences at the end of the file (it had an additional appendix). So the method https://github.com/project-ncl/build-finder/blob/master/core/src/main/java/org/jboss/pnc/build/finder/core/LicenseUtils.java#L599C20-L599C118 returned an Optional.Empty (as expected). The issue was in the method https://github.com/project-ncl/build-finder/blob/master/core/src/main/java/org/jboss/pnc/build/finder/core/LicenseUtils.java#L553  because in the above case, https://github.com/project-ncl/build-finder/blob/master/core/src/main/java/org/jboss/pnc/build/finder/core/LicenseUtils.java#L559 found an Optional<Optional.Empty> and prevented the https://github.com/project-ncl/build-finder/blob/master/core/src/main/java/org/jboss/pnc/build/finder/core/LicenseUtils.java#L560 to be executed (preventing the analysis only the first 5 lines of the licenseText).

I have solved the issue changing https://github.com/project-ncl/build-finder/blob/master/core/src/main/java/org/jboss/pnc/build/finder/core/LicenseUtils.java#L553 to become:
`    public static Optional<String> findMatchingLicense(FileObject licenseFileObject) {
        try (FileContent fc = licenseFileObject.getContent(); InputStream in = fc.getInputStream()) {
            String licenseText = new String(in.readAllBytes(), UTF_8);
            return LICENSE_ID_TEXT_LIST.stream()
                    .map(id -> LICENSE_ID_MAP.get(id))
                    .map(license -> findMatchingSPDXLicenseIdentifier(license, licenseText))
                    .flatMap(Optional::stream)
                    .findAny()
                    .or(() -> findMatchingSPDXLicenseIdentifierOrLicense(licenseText));
        } catch (IOException e) {
            return Optional.empty();
        }
    }`
The flatMap reduction allows to get rid of Optional.Empty values, and thus allows the execution of the `findMatchingSPDXLicenseIdentifierOrLicense(licenseText)` method, allowing to find a match for the license!

If you agree with the above change, would you mind adding this to your PR? And consider it approved from me to be merged :-D

**Review by vibe13 — CHANGES_REQUESTED** [review]
Please see the change I have suggested to fix the issue. My tests showed the detection of more licenses (less `NOASSERTION` in the license text). Other than that, +1! Thanks!

**Comment by vibe13** [comment]
@dwalluck Actually, I am also looking at the "[ERROR] No matching archive found for file" errors messages, trying to get the root cause. The checksums are there and a build is found for them, and added to the builds, so not sure why the above happens

**Comment by dwalluck** [comment]
> Please see the change I have suggested to fix the issue. My tests showed the detection of more licenses (less `NOASSERTION` in the license text). Other than that, +1! Thanks!

I am going to add your change on the original PR and force push. I knew the use of `orElseGet` instead of `or` there should have clued me in to what was happening.

I am not sure if the test in this PR is still useful as I obviously didn't trigger the bug.

**Comment by vibe13** [comment]
@dwalluck ok great, let's keep the test anyway as it does not hurt. we can marge this one and address the  "[ERROR] No matching archive found for file" bug in another PR because it's not related to this work. Thanks!

**Review by vibe13 — APPROVED** [review]

**Pull request merged**
